services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - etf_data:/app/data
    ports:
      - "9528:9528"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  etf_data:
